apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: petclinic 
  namespace: petclinic
  labels: 
    app: petclinic 
    service: petclinic 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: petclinic 
  template: 
    metadata: 
      labels: 
        app: petclinic 
        service: petclinic 
    spec: 
      dnsPolicy: ClusterFirstWithHostNet 
      containers: 
      - name: petclinic 
        image: eyalkoren/pet-clinic:without-agent